services:
  - type: web
    name: pg-mcp
    env: docker
    plan: standard
    autoDeploy: true
    dockerfilePath: ./Dockerfile
    dockerCommand: uv run -m server.app
    envVars:
      - key: LOG_LEVEL
        value: INFO
      - key: PYTHONUNBUFFERED
        value: 1
    numInstances: 1
    region: virginia
    
